### PR TITLE
Better XMLMetadata parsing

### PR DESCRIPTION
**Pull request by artem-smotrakov**

### CODE REVIEW

**Comment by mibo** [comment]
Hi Artem, Thanks for your contribution.
I did one minor change and applied our code formatter.
If both is fine for you I will squash the commits and merge it onto the master.
Kind Regards, Michael

**Comment by artem-smotrakov** [comment]
@mibo The changes look fine to me. Thanks for the help!

**Comment by mibo** [comment]
@artem-smotrakov Thanks for the contribution 👍  🙂

**Comment by jBuchholz590** [comment]
Hi,
in this PR you modified the way metadata is parsed in the `AbstractService`.
A new function `getAllowedClasses` was introduced to provide classes that may be deserialized.

Can you tell me how this would be used in conjuntion with the pojogen-maven-plugin?
In the service template (`service.vm`) this function is not given so in my understanding there is no way to utilize it with the plugin?

Kind regards,
Jan

**Pull request merged**
