### PR TITLE
[OLINGO-1377] add condition for parsing "floating" value of Scale facet type

### PR DESCRIPTION
**Pull request by devanshsoni9**
https://issues.apache.org/jira/browse/OLINGO-1377

I did not see any tests for "variable" value so I am not sure if/where I need to add tests for "floating"

### CODE REVIEW

**Comment by devanshsoni9** [comment]
Hi @mibo, can you help review my pull request. They have been there for some time now

Thanks 
Devansh

**Comment by mibo** [comment]
Hi @devanshsoni9 , yes I promise that I will review it in the next days.

**Comment by devanshsoni9** [comment]
Thanks @mibo 👍

**Comment by devanshsoni9** [comment]
Thanks for merging this @mibo. 
I wanted to know when is the next release of olingo to determine if I should wait for it or build the jar  locally and integrate that into my code base.

**Comment by devanshsoni9** [comment]
Hi @mibo 
It would be great if you can answer my question about the next release date.

Thanks 
Devansh

**Comment by devanshsoni9** [comment]
Thanks @mibo

**Pull request merged**
