### PR TITLE
[OLINGO-1600] Upgrade JDK 17 + Jakarta + Spring (6)

### PR DESCRIPTION
**Pull request by mibo**

### CODE REVIEW

**Comment by mibo** [comment]
Quick update, I plan to provide a `5.0.0-ALPHA` version to give all an easy option to test the upgrade.
Most likely the version will be available by this weekend.

**Comment by mibo** [comment]
I uploaded the alpha release build. It should soon be available in [Maven central](https://search.maven.org/search?q=g:org.apache.olingo).

It is based on this PR, please test it and provide feedback.
I will take some time and do another review round in the next days.
Based on this and the feedback I will provide another alpha version or proceed with the 5.0.0 release.

**Comment by eduardoraupp** [comment]
> I uploaded the alpha release build. It should soon be available in [Maven central](https://search.maven.org/search?q=g:org.apache.olingo) (already in [Sonatype nexus](https://central.sonatype.com/search?q=org.apache.olingo&smo=true&sort=published&namespace=org.apache.olingo)).
> 
> It is based on this PR, please test it and provide feedback. I will take some time and do another review round in the next days. Based on this and the feedback I will provide another alpha version or proceed with the 5.0.0 release.

Thank you for accepting my PR @mibo. I will keep working on the framework evolution! I hope also become a committer soon!!! :)

**Comment by mibo** [comment]
Created a [5.0.0-ALPHA-02](https://search.maven.org/search?q=g:org.apache.olingo&v=5.0.0-ALPHA-02) with some additional dependency updates.

**Comment by mibo** [comment]
I tested some of the Olingo samples with the [5.0.0-ALPHA-02](https://search.maven.org/search?q=g:org.apache.olingo&v=5.0.0-ALPHA-02) and everything worked as expected.

I plan to continue with the release if there are no objections.

**Comment by danishnawab** [comment]
> I tested some of the Olingo samples with the [5.0.0-ALPHA-02](https://search.maven.org/search?q=g:org.apache.olingo&v=5.0.0-ALPHA-02) and everything worked as expected.
> 
> I plan to continue with the release if there are no objections.

I have already successfully used the 5.x ALPHA in production without any issues. So I welcome a full release.

**Comment by danishnawab** [comment]
@mibo do you have an estimate on when 5.0.0 will be available for general use?

**Comment by sangeetrathore1** [comment]
What is release plan for Olingo 5.x.x?

**Comment by rarathore** [comment]
What is release plan for Olingo 5.x.x?

**Pull request merged**
