### PR TITLE
Fixing batch-request rollback

### PR DESCRIPTION
**Pull request by madhawa-gunasekara**
Hi Devs, 

We don't need to commit if the request is failed. we just need to rollback. but after doing rollback we don't need to commit. Please review and merge.

Thanks,
Madhawa

### CODE REVIEW

**Comment by madhawa-gunasekara** [comment]
@rareddy Can you please review this ?

**Comment by rareddy** [comment]
Pulled the change, but lost your credentials to the commit along the way. As you see this project is not hosted on GitHub, it is just a mirror copy, so I have to pull locally and then commit.  So, I did a patch file and then merged it. The patch had your credentials but not sure why it did not show up in the commit. Hope that is OK.

**Comment by madhawa-gunasekara** [comment]
yes, no problem

**Comment by rareddy** [comment]
Also please close this.

**Pull request closed without merging**
