### PR TITLE
[Olingo 1408] Java 8 DateTime API support by Olingo

### PR DESCRIPTION
**Pull request by mibo**
As the initial #57 was approved I created this branch to make the code formatting and merge easier because I have not expected any issue.
However some test failed which I fixed with commit `ec603917e` but still one test fails (see `org.apache.olingo.server.tecsvc.data.DataProviderTest.esAllKeyEntity(DataProviderTest.java:71)`).

Can you Adrian @agoerler or you  Ramya @i050510 please have a look into as you both worked on the PR before.

Thanks in advance, Michael

### CODE REVIEW

**Comment by i050510** [comment]
I will fix it.

Thanks,
Ramya

**Comment by mibo** [comment]
Hi Ramya (@i050510),
Thanks for fixing and please let me know when you are done as afterwards I would start with the release preparation.

Kind Regards, Michael

**Comment by i050510** [comment]
Hi Michael,
Tests are fixed and I have pushed the changes
https://git-wip-us.apache.org/repos/asf?p=olingo-odata4.git;a=commit;h=636fdde13dda35d9decae1768d9846f04bb355d9

Regards,
Ramya

**Comment by mibo** [comment]
Thanks Ramya, I will then merge it and when everything work I will start with the release preparation.

Kind Regards, Michael

**Pull request merged**
