### PR TITLE
OLINGO-1551 Update parent, plugin versions and dependencies

### PR DESCRIPTION
**Pull request by dheid**
Hi @mibo!

The projects parent from Apache, many dependencies and some Maven plugins are outdated. I updated the Apache parent and some of the low hanging fruits (easy to update, bringing some more compatibility for client applications and do not conflict).

Regards,
Daniel

[OLINGO-1551](https://issues.apache.org/jira/browse/OLINGO-1551)

### CODE REVIEW

**Comment by dheid** [comment]
@mibo @archanarai2211 Is this project still alive?

**Comment by mibo** [comment]
Hi @dheid,
Yes, the project is still alive. The delay was mainly because of vacation and other topics which keeps me busy 🙃
Thanks for the contribution, will check and merge soon.
Furthermore a new release is planned and should be available this month.
Kind Regards, Michael

**Comment by mibo** [comment]
Relates to [OLINGO-1551](https://issues.apache.org/jira/browse/OLINGO-1551)

**Comment by dheid** [comment]
Thank you very much @mibo !!!

**Pull request merged**
